name: myoConverter
channels:
  - opensim-org
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.16
  - mujoco
  # - mujoco-python=2.3.3
  - loguru=0.5.3
  - lxml=4.9.1
  - numpy=1.21.5
  - scipy=1.10.0
  - scikit-learn=1.2.0
  - opensim=4.4
  - matplotlib=3.6.2
  - trimesh=3.22.2
  - pyvista=0.39.1
  - networkx=2.8.4
  - fpdf2=2.7.4
  - seaborn=0.12.2
